### ISSUE TITLE
melt_table2 crashing R session

### ISSUE THREAD

**Issue by skiamu** [jimhester/meltr#10]
Hi,

here's my MRE ([XXX.txt](https://github.com/r-lib/meltr/files/7545763/XXX.txt))
`meltr::melt_table2("XXX.txt")`

result: 
![image](https://user-images.githubusercontent.com/16693811/141975542-24a1e142-5213-4b39-9ecc-1a9321a7c50c.png)

Here's my session info:
![image](https://user-images.githubusercontent.com/16693811/141976041-748fecc5-e19e-4fdc-aac6-4349349c4b6f.png)

If it is of any help I'll attach my Windows Event Viewer logs
![image](https://user-images.githubusercontent.com/16693811/141976507-73771b96-4e8e-4005-9fb3-c89a27c2fca1.png)

--------------------------------------------------------------------------------------------------------

Could the problem be this one?
![image](https://user-images.githubusercontent.com/16693811/141993275-e4ee3068-2972-426c-888f-a58c379a1400.png)

**Comment by AndLLA** [comment]
I had the exactly same problem and I (temporarily) fixed it by enlarging the buffer size,
maybe we should check the buffer size vs expected_size+1 before copying ?
