### ISSUE TITLE
Release meltr 1.0.0

### ISSUE THREAD

**Issue by jimhester** [jimhester/meltr#4]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Proof read `Title:` and `Description:`
* [x] Check that all exported functions have `@returns` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `devtools::build_readme()`
* [x] [`urlchecker::url_check()`](https://github.com/r-lib/urlchecker)
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `rhub::check(platform = 'ubuntu-rchk')`
* [x] `rhub::check_with_sanitizers()`
* [ ] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_news_md()`
* [x] `usethis::use_dev_version()`
* [x] Update install instructions in README
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by jimhester** [comment]
Hi @nacnudus, I think this package is generally ready for a first release.

If you could go through this checklist updating this as needed and verify everything looks good I think we could release it.

If you would like me to review any changes you make before you submit I would be happy to do so.

**Comment by nacnudus** [comment]
### Advice needed

I think these potential problems can be ignored, but I'd appreciate your advice @jimhester.

1. `devtools::check(remote = TRUE, manual = TRUE)` gives a NOTE: "Compilation used the following non-portable flag(s): ‘-march=x86-64’". I think it can be ignored.
2. `rhub::check(platform = 'ubuntu-rchk')` fails with PREPERROR (compilation failed for package 'meltr')
3. `rhub::check_with_sanitizers()` fails with PREPERROR (compilation failed for package 'meltr')
4. `devtools::document()` gives warnings that seem to be related to https://github.com/r-lib/roxygen2/issues/931.  They are R6 methods, defined dynamically, so that it doesn't seem possible to document them.

<details>
<summary>Show warnings</summary>

```text
> devtools::document()
ℹ Updating meltr documentation
ℹ Loading meltr
Writing NAMESPACE
Warning: [/home/nacnudus/R/meltr/R/callback.R:31] undocumented R6 methods: `initialize`, `receive`, `continue`, `result`, `finally`
Warning: [/home/nacnudus/R/meltr/R/callback.R:36] argument `callback` undocumented for R6 method `initialize()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:37] argument `data` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:37] argument `index` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:48] undocumented R6 methods: `initialize`, `receive`, `continue`
Warning: [/home/nacnudus/R/meltr/R/callback.R:54] argument `callback` undocumented for R6 method `initialize()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:58] argument `data` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:58] argument `index` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:72] undocumented R6 methods: `initialize`, `receive`, `result`, `finally`
Warning: [/home/nacnudus/R/meltr/R/callback.R:78] argument `callback` undocumented for R6 method `initialize()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:81] argument `data` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:81] argument `index` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:98] undocumented R6 methods: `initialize`, `receive`, `result`, `finally`
Warning: [/home/nacnudus/R/meltr/R/callback.R:104] argument `callback` undocumented for R6 method `initialize()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:107] argument `data` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:107] argument `index` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:124] undocumented R6 methods: `initialize`, `receive`, `result`
Warning: [/home/nacnudus/R/meltr/R/callback.R:130] argument `callback` undocumented for R6 method `initialize()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:130] argument `acc` undocumented for R6 method `initialize()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:138] argument `data` undocumented for R6 method `receive()`
Warning: [/home/nacnudus/R/meltr/R/callback.R:138] argument `index` undocumented for R6 method `receive()`
Registered S3 methods overwritten by 'readr':
  method           from 
  print.date_names meltr
  print.locale     meltr
Writing NAMESPACE
```

</details>

### extrachecks

These are tasks to be completed to meet https://github.com/DavisVaughan/extrachecks

- [x] Add `@returns` to exported functions:
    - [x]  `show_progress()`
    - [x] `datasource()`
    - [x] `locale()`
    - [x] `melt_fwf()`
    - [x] `melt_delim()`
    - [x] `melt_delim_chunked()`
    - [x] `melt_table()`
    - [x] `tokenizer_delim()`
    - [x] `date_names()`
    - [x] `meltr_example()`

- [x] Add `@examples` to exported functions:
    - [x]  `show_progress()`
    - [x] `clipboard()`
    - [x] Callback classes?

- [x] `DESCRIPTION` proposed 'Description:' "The goal of 'meltr' is to provide a fast and friendly way to non-rectangular data, such as ragged forms of csv (comma-separated values), tsv (tab-separated values), and fwf (fixed-width format) files." to meet the requirements:
    - [x] "Functions do not need to be put in single quotes, just packages, software names and API names."  Presumably file formats do not need to be put in single quotes.
    - [x] "Please always explain all acronyms/abbreviations in the description text in the Description field of the DESCRIPTION"

**Comment by jimhester** [comment]
1. This flag is likely added by your personal or site makevars, as meltr itself doesn't use a Makevars file. You are right it can be ignored.
2.,3. I guess we need to figure out why the PREPERROR is happening. Could you link to the logs of the failures? I re-ran the ubuntu-rchk one just now and [it worked](https://builder.r-hub.io/status/meltr_0.0.0.9000.tar.gz-f64c897d62ac4cf5b8a5a967a2b76517), it is possible you were running into an issue with a dependency which is now fixed. You may want to try re-running the sanitizer one to be sure.
4. These warnings can be ignored, they are somewhat valid but I don't think it is very important to document these methods for readr or meltr.

**Comment by nacnudus** [comment]
I've fixed all the items described above.

1. `rhub::check_with_sanitizers()` still fails with a PREPERROR [html build log](https://builder.r-hub.io/status/meltr_0.0.0.9000.tar.gz-3769d892784d4b978d95b9f0c1a21234)
2. `rhub::check(platform = 'ubuntu-rchk')` fails with an ERROR [html build log](https://builder.r-hub.io/status/meltr_0.0.0.9000.tar.gz-a3b2bcf546f94757afb8927446e75beb)
3. The GitHub action [fails](https://github.com/r-lib/meltr/actions/runs/1133346559) on Windows latest (release), but I'm not worried about that.

**Comment by jimhester** [comment]
The rhub sanitizer error looks like the compiler is not using C++11, if you add `SystemRequirements: C++11` to the `DESCRIPTION` I think they should be fixed.

The rchk results are clean though.

None of the things raised in https://builder.r-hub.io/status/meltr_0.0.0.9000.tar.gz-a3b2bcf546f94757afb8927446e75beb#L2575 are true rchk issues, the tool is just saying it can't analyze the given functions for various reasons.

**Comment by jimhester** [comment]
I think you can submit this to CRAN whenever you are ready to do so, it looks good to me assuming the system requirements change fixes the sanitizer failures.

**Comment by nacnudus** [comment]
It is on [CRAN](https://cran.r-project.org/web/checks/check_results_meltr.html).

Should it have a pkgdown site on r-lib.org?  If so, is there a process to follow?

**Comment by jimhester** [comment]
I think it is fine to leave the pkgdown site at https://r-lib.github.io/meltr/ for now.

**Comment by jimhester** [comment]
Also congrats for the successful CRAN submission 🎉!

**Comment by nacnudus** [comment]
Thanks, and thanks for doing almost all the work!
