### ISSUE TITLE
Probably don't need tzdb

### ISSUE THREAD

**Issue by DavisVaughan** [jimhester/meltr#6]
Since results are always character, and never POSIXct/Date?

The `locale()` helper, `check_tz()`, uses a tzdb helper to check if a valid `tz` argument is provided, but I don't think the `tz` argument would ever be used by meltr so that could probably be removed to

**Comment by jimhester** [comment]
Yeah, that sounds right, I removed the other TZ specific code but not yet this.

**Comment by jimhester** [comment]
Closed by https://github.com/r-lib/meltr/commit/213e6f8e68a636202360ef5b177a399c35b29fb8
